- 사본 생성 후 수정 부탁드립니다.
- 과제1과 과제2 모두 수행 후, 결과를 포함한 ipynb 파일을 제출해 주세요. (파일명은 이름_pandas_numpy_과제.ipynb로 부탁드립니다.)
- 출력하는 데 너무 오래 걸린다면 상위 30개만 출력해 주세요.

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## 과제1
- 데이터: wine.csv (와인 성분 변수들을 이용하여 품질을 예측하는 데이터)

In [4]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import warnings
warnings.filterwarnings(action='ignore')

#### 데이터 불러오기 및 앞부분 확인

In [6]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [7]:
data = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/wine.csv') # wine.csv: '내 드라이브'에 사본 저장 후, 경로 수정

data.head()

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,white
1,1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,red
2,2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,white
3,3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,white
4,4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,white

In [8]:
# 인덱스 컬럼 드랍하기
data = data.drop("index", axis = 1)
data.head()

,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,white
1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,red
2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,white
3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,white
4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,white

#### 데이터 shape 확인

In [9]:
data.shape

(5497, 13)

#### 컬럼명 확인

In [10]:
data.columns

Index(['quality', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'type'],
      dtype='object')

#### NaN, 데이터 타입, 개수 확인

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5497 entries, 0 to 5496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   quality               5497 non-null   int64
 1   fixed acidity         5497 non-null   float64
 2   volatile acidity      5497 non-null   float64
 3   citric acid           5497 non-null   float64
 4   residual sugar        5497 non-null   float64
 5   chlorides             5497 non-null   float64
 6   free sulfur dioxide   5497 non-null   float64
 7   total sulfur dioxide  5497 non-null   float64
 8   density               5497 non-null   float64
 9   pH                    5497 non-null   float64
 10  sulphates             5497 non-null   float64
 11  alcohol               5497 non-null   float64
 12  type                  5497 non-null   object
dtypes: float64(11), int64(1), object(1)
memory usage: 558.4+ KB

#### 통계값 확인

In [12]:
data.describe()

,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
count,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000
mean,5.818992,7.210115,0.338163,0.318543,5.438075,0.055808,30.417682,115.566491,0.994673,3.219502,0.530524,10.504918
std,0.870311,1.287579,0.163224,0.145104,4.756676,0.034653,17.673881,56.288223,0.003014,0.160713,0.149396,1.194524
min,3.000000,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.740000,0.220000,8.000000
25%,5.000000,6.400000,0.230000,0.250000,1.800000,0.038000,17.000000,78.000000,0.992300,3.110000,0.430000,9.500000
50%,6.000000,7.000000,0.290000,0.310000,3.000000,0.047000,29.000000,118.000000,0.994800,3.210000,0.510000,10.300000
75%,6.000000,7.700000,0.400000,0.390000,8.100000,0.064000,41.000000,155.000000,0.996930,3.320000,0.600000,11.300000
max,9.000000,15.900000,1.580000,1.660000,65.800000,0.610000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000

#### quality의 unique 확인

In [13]:
data.quality.unique()

array([5, 6, 7, 8, 4, 3, 9])

#### quality별로 개수 확인

In [14]:
data.quality.value_counts()

6    2416
5    1788
7     924
4     186
8     152
3      26
9       5
Name: quality, dtype: int64

#### 다음 컬럼만 따로 데이터프레임으로 추출해라 : 'quality', 'residual sugar', 'pH', 'alcohol', 'type'

In [15]:
data_sample = data[['quality', 'residual sugar', 'pH', 'alcohol', 'type']]
data_sample.head()

   quality  residual sugar    pH  alcohol   type
0        5             6.8  3.44     10.2  white
1        5             2.4  3.19      9.5    red
2        5             2.0  3.05     10.9  white
3        6             6.0  3.26     10.8  white
4        6             9.5  3.04     10.9  white

#### groupby를 통해 quality로 묶고 통계값(min,mean,max) 확인

In [16]:
#min
data_sample.groupby('quality').min()

         residual sugar    pH  alcohol   type
quality
3                  1.15  2.87      8.0    red
4                  0.70  2.74      8.6    red
5                  0.60  2.79      8.0    red
6                  0.70  2.74      8.4    red
7                  0.90  2.84      8.6    red
8                  0.80  2.94      8.8    red
9                  1.60  3.20     10.4  white

In [17]:
#mean
data_sample.groupby('quality').mean()

         residual sugar        pH    alcohol
quality
3              5.203846  3.250385  10.251923
4              4.145430  3.228602  10.180376
5              5.792422  3.213384   9.846875
6              5.535141  3.219611  10.606015
7              4.748918  3.228333  11.383864
8              5.581579  3.216711  11.680921
9              4.120000  3.308000  12.180000

In [18]:
#max
data_sample.groupby('quality').max()

         residual sugar    pH  alcohol   type
quality
3                 16.20  3.63     12.6  white
4                 15.40  3.90     13.5  white
5                 23.50  3.79     14.9  white
6                 65.80  4.01     14.0  white
7                 19.25  3.82     14.2  white
8                 14.80  3.57     14.0  white
9                 10.60  3.41     12.9  white

#### 알코올 함량을 기준으로 오름차순 정리  / 상위 30개만 출력

In [19]:
data.sort_values('alcohol').head(30)

,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
4254,3,4.2,0.215,0.23,5.10,0.041,64.0,157.0,0.99688,3.42,0.44,8.0,white
5077,5,4.5,0.190,0.21,0.95,0.033,89.0,159.0,0.99332,3.34,0.42,8.0,white
1768,3,10.4,0.610,0.49,2.10,0.200,5.0,16.0,0.99940,3.16,0.63,8.4,red
4176,5,6.2,0.310,0.23,3.30,0.052,34.0,113.0,0.99429,3.16,0.48,8.4,white
479,6,14.3,0.310,0.74,1.80,0.075,6.0,15.0,1.00080,2.86,0.79,8.4,red
3725,5,7.6,0.280,0.49,20.15,0.060,30.0,145.0,1.00196,3.01,0.44,8.5,white
3772,6,6.4,0.180,0.48,18.00,0.054,56.0,183.0,1.00038,2.98,0.61,8.5,white
172,6,6.5,0.180,0.48,18.00,0.054,56.0,183.0,1.00038,2.98,0.61,8.5,white
255,5,10.0,0.380,0.38,1.60,0.169,27.0,90.0,0.99914,3.15,0.65,8.5,red
3062,5,6.1,0.430,0.35,9.10,0.059,83.0,249.0,0.99710,3.37,0.50,8.5,white
2377,5,6.5,0.360,0.16,1.30,0.054,11.0,107.0,0.99398,3.19,0.39,8.5,white
1427,6,6.3,0.200,0.30,5.90,0.034,35.0,152.0,0.99642,3.47,0.40,8.5,white
4249,4,7.2,0.400,0.62,10.80,0.041,70.0,189.0,0.99760,3.08,0.49,8.6,white
3155,4,6.5,0.270,0.19,4.20,0.046,6.0,114.0,0.99550,3.25,0.35,8.6,white
4224,6,6.8,0.220,0.24,4.90,0.092,30.0,123.0,0.99510,3.03,0.46,8.6,white
3046,5,7.3,0.310,0.69,10.20,0.041,58.0,160.0,0.99770,3.06,0.45,8.6,white
3640,7,8.0,0.220,0.42,14.60,0.044,45.0,163.0,1.00030,3.21,0.69,8.6,white
30,5,6.8,0.440,0.20,16.00,0.065,61.0,186.0,0.99884,3.13,0.45,8.6,white
3656,5,6.9,0.270,0.49,23.50,0.057,59.0,235.0,1.00240,2.98,0.47,8.6,white
3355,4,7.3,0.360,0.54,13.30,0.054,63.0,193.0,0.99864,3.06,0.49,8.6,white
5043,5,7.3,0.310,0.69,10.20,0.041,58.0,160.0,0.99770,3.06,0.45,8.6,white
373,5,7.7,0.340,0.58,11.10,0.039,41.0,151.0,0.99780,3.06,0.49,8.6,white
2111,5,6.0,0.210,0.29,13.10,0.042,28.0,125.0,0.99936,3.39,0.45,8.6,white
55,7,8.0,0.220,0.42,14.60,0.044,45.0,163.0,1.00030,3.21,0.69,8.6,white
5066,5,6.1,0.340,0.31,12.00,0.053,46.0,238.0,0.99770,3.16,0.48,8.6,white
5302,6,6.8,0.270,0.28,13.30,0.076,50.0,163.0,0.99790,3.03,0.38,8.6,white
686,5,8.3,0.360,0.57,15.00,0.052,35.0,256.0,1.00010,2.93,0.64,8.6,white
4615,5,7.3,0.240,0.39,17.95,0.057,45.0,149.0,0.99990,3.21,0.36,8.6,white
5353,4,7.2,0.400,0.62,10.80,0.041,70.0,189.0,0.99760,3.08,0.49,8.6,white
4869,5,7.7,0.340,0.58,11.10,0.039,41.0,151.0,0.99780,3.06,0.49,8.6,white

#### quailty가 7 이상인 데이터 추출 (20개)

In [20]:
data[data.quality >= 7].head(20)

,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
11,7,6.2,0.160,0.33,1.10,0.057,21.0,82.0,0.99100,3.32,0.46,10.9,white
12,7,7.3,0.330,0.40,6.85,0.038,32.0,138.0,0.99200,3.03,0.30,11.9,white
17,7,6.5,0.280,0.25,4.80,0.029,54.0,128.0,0.99074,3.17,0.44,12.2,white
25,8,6.6,0.290,0.31,3.90,0.027,39.0,96.0,0.99035,3.24,0.60,12.6,white
45,7,7.5,0.305,0.38,1.40,0.047,30.0,95.0,0.99158,3.22,0.52,11.5,white
46,7,7.4,0.190,0.30,12.80,0.053,48.5,212.0,0.99860,3.14,0.49,9.1,white
53,7,6.6,0.290,0.29,1.80,0.036,38.0,102.0,0.98819,3.08,0.42,13.7,white
54,8,7.0,0.530,0.43,6.10,0.029,6.0,76.0,0.99118,3.08,0.50,12.5,white
55,7,8.0,0.220,0.42,14.60,0.044,45.0,163.0,1.00030,3.21,0.69,8.6,white
60,7,6.2,0.290,0.32,3.60,0.026,39.0,138.0,0.98920,3.31,0.37,13.1,white
63,7,8.3,0.280,0.48,2.10,0.093,6.0,12.0,0.99408,3.26,0.62,12.4,red
71,8,6.8,0.190,0.32,7.05,0.019,54.0,188.0,0.99350,3.25,0.37,11.1,white
74,7,6.0,0.100,0.24,1.10,0.041,15.0,65.0,0.99270,3.61,0.61,10.3,white
79,7,6.2,0.200,0.26,1.10,0.047,42.0,119.0,0.99158,3.48,0.60,11.0,white
87,7,5.0,0.270,0.32,4.50,0.032,58.0,178.0,0.98956,3.45,0.31,12.6,white
89,7,7.6,0.310,0.24,1.80,0.037,39.0,150.0,0.99130,3.05,0.44,11.8,white
101,7,6.4,0.310,0.38,2.90,0.038,19.0,102.0,0.99120,3.17,0.35,11.0,white
104,7,7.1,0.270,0.27,10.40,0.041,26.0,114.0,0.99335,3.04,0.52,11.5,white
119,7,6.7,0.250,0.33,2.90,0.057,52.0,173.0,0.99340,3.02,0.48,9.5,white
120,7,5.6,0.350,0.40,6.30,0.022,23.0,174.0,0.99220,3.54,0.50,11.6,white

#### 'strength' 컬럼추가 : alcohol을 기준으로 10도가 넘으면 'strong' 아니면 'weak'으로 표시 (상위 30개만 출력)

In [21]:
def is_strong(alcohol):
    if alcohol < 10 :
        return 'weak'
    else :
        return 'strong'

In [23]:
data['strength'] = data['alcohol'].apply(is_strong)
data.head(30)

,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type,strength
0,5,5.6,0.695,0.06,6.80,0.042,9.0,84.0,0.99432,3.44,0.44,10.20,white,strong
1,5,8.8,0.610,0.14,2.40,0.067,10.0,42.0,0.99690,3.19,0.59,9.50,red,weak
2,5,7.9,0.210,0.39,2.00,0.057,21.0,138.0,0.99176,3.05,0.52,10.90,white,strong
3,6,7.0,0.210,0.31,6.00,0.046,29.0,108.0,0.99390,3.26,0.50,10.80,white,strong
4,6,7.8,0.400,0.26,9.50,0.059,32.0,178.0,0.99550,3.04,0.43,10.90,white,strong
5,6,6.0,0.190,0.37,9.70,0.032,17.0,50.0,0.99320,3.08,0.66,12.00,white,strong
6,5,6.1,0.220,0.49,1.50,0.051,18.0,87.0,0.99280,3.30,0.46,9.60,white,weak
7,6,7.1,0.380,0.42,11.80,0.041,32.0,193.0,0.99624,3.04,0.49,10.00,white,strong
8,5,6.8,0.240,0.31,18.30,0.046,40.0,142.0,1.00000,3.30,0.41,8.70,white,weak
9,5,6.8,0.390,0.35,11.60,0.044,57.0,220.0,0.99775,3.07,0.53,9.30,white,weak
10,6,8.0,0.180,0.37,0.90,0.049,36.0,109.0,0.99007,2.89,0.44,12.70,red,strong
11,7,6.2,0.160,0.33,1.10,0.057,21.0,82.0,0.99100,3.32,0.46,10.90,white,strong
12,7,7.3,0.330,0.40,6.85,0.038,32.0,138.0,0.99200,3.03,0.30,11.90,white,strong
13,5,7.1,0.310,0.17,1.00,0.042,21.0,144.0,0.99304,3.13,0.40,9.60,white,weak
14,5,12.5,0.380,0.60,2.60,0.081,31.0,72.0,0.99960,3.10,0.73,10.50,red,strong
15,5,7.8,0.490,0.49,7.00,0.043,29.0,149.0,0.99520,3.21,0.33,10.00,white,strong
16,5,8.8,0.370,0.48,2.10,0.097,39.0,145.0,0.99750,3.04,1.03,9.30,red,weak
17,7,6.5,0.280,0.25,4.80,0.029,54.0,128.0,0.99074,3.17,0.44,12.20,white,strong
18,6,8.2,0.230,0.40,7.50,0.049,12.0,76.0,0.99660,3.06,0.84,9.70,white,weak
19,6,6.8,0.310,0.25,10.50,0.043,30.0,165.0,0.99720,3.36,0.55,10.55,white,strong
20,5,7.6,0.310,0.26,1.70,0.073,40.0,157.0,0.99380,3.10,0.46,9.80,white,weak
21,5,7.2,0.560,0.26,2.00,0.083,13.0,100.0,0.99586,3.26,0.52,9.90,red,weak
22,6,7.1,0.210,0.33,1.20,0.039,34.0,97.0,0.99112,3.11,0.75,11.20,white,strong
23,6,7.7,0.715,0.01,2.10,0.064,31.0,43.0,0.99371,3.41,0.57,11.80,red,strong
24,5,8.9,0.750,0.14,2.50,0.086,9.0,30.0,0.99824,3.34,0.64,10.50,red,strong
25,8,6.6,0.290,0.31,3.90,0.027,39.0,96.0,0.99035,3.24,0.60,12.60,white,strong
26,5,6.3,0.310,0.34,2.20,0.045,20.0,77.0,0.99270,3.30,0.43,10.20,white,strong
27,5,6.1,0.360,0.58,15.00,0.044,42.0,115.0,0.99780,3.15,0.51,9.00,white,weak
28,6,6.1,0.410,0.00,1.60,0.063,36.0,87.0,0.99140,3.27,0.67,10.80,white,strong
29,4,7.6,0.260,0.36,1.60,0.032,6.0,106.0,0.99300,3.15,0.40,10.40,white,strong

#### merge 실습을 위한 데이터 쪼개기

In [26]:
df_x = data[['quality', 'fixed acidity', 'citric acid']].head(30)

In [27]:
df_y = data[['quality', 'volatile acidity', 'chlorides', 'alcohol']].head(30)

In [28]:
df_y = df_y[df_y.quality >= 7]

In [38]:
len(df_y)

4

#### df_x와 df_y를 inner join시키기 (quality를 기준으로)

In [39]:
pd.merge(df_x, df_y, how = 'inner', on = 'quality')

   quality  fixed acidity  citric acid  volatile acidity  chlorides  alcohol
0        7            6.2         0.33              0.16      0.057     10.9
1        7            6.2         0.33              0.33      0.038     11.9
2        7            6.2         0.33              0.28      0.029     12.2
3        7            7.3         0.40              0.16      0.057     10.9
4        7            7.3         0.40              0.33      0.038     11.9
5        7            7.3         0.40              0.28      0.029     12.2
6        7            6.5         0.25              0.16      0.057     10.9
7        7            6.5         0.25              0.33      0.038     11.9
8        7            6.5         0.25              0.28      0.029     12.2
9        8            6.6         0.31              0.29      0.027     12.6

#### df_x에서 df_y를 left join시키기 (quality를 기준으로)

In [40]:
pd.merge(df_x, df_y, how = 'left', on = 'quality')

    quality  fixed acidity  citric acid  volatile acidity  chlorides  alcohol
0         5            5.6         0.06               NaN        NaN      NaN
1         5            8.8         0.14               NaN        NaN      NaN
2         5            7.9         0.39               NaN        NaN      NaN
3         6            7.0         0.31               NaN        NaN      NaN
4         6            7.8         0.26               NaN        NaN      NaN
5         6            6.0         0.37               NaN        NaN      NaN
6         5            6.1         0.49               NaN        NaN      NaN
7         6            7.1         0.42               NaN        NaN      NaN
8         5            6.8         0.31               NaN        NaN      NaN
9         5            6.8         0.35               NaN        NaN      NaN
10        6            8.0         0.37               NaN        NaN      NaN
11        7            6.2         0.33              0.16      0.057     10.9
12        7            6.2         0.33              0.33      0.038     11.9
13        7            6.2         0.33              0.28      0.029     12.2
14        7            7.3         0.40              0.16      0.057     10.9
15        7            7.3         0.40              0.33      0.038     11.9
16        7            7.3         0.40              0.28      0.029     12.2
17        5            7.1         0.17               NaN        NaN      NaN
18        5           12.5         0.60               NaN        NaN      NaN
19        5            7.8         0.49               NaN        NaN      NaN
20        5            8.8         0.48               NaN        NaN      NaN
21        7            6.5         0.25              0.16      0.057     10.9
22        7            6.5         0.25              0.33      0.038     11.9
23        7            6.5         0.25              0.28      0.029     12.2
24        6            8.2         0.40               NaN        NaN      NaN
25        6            6.8         0.25               NaN        NaN      NaN
26        5            7.6         0.26               NaN        NaN      NaN
27        5            7.2         0.26               NaN        NaN      NaN
28        6            7.1         0.33               NaN        NaN      NaN
29        6            7.7         0.01               NaN        NaN      NaN
30        5            8.9         0.14               NaN        NaN      NaN
31        8            6.6         0.31              0.29      0.027     12.6
32        5            6.3         0.34               NaN        NaN      NaN
33        5            6.1         0.58               NaN        NaN      NaN
34        6            6.1         0.00               NaN        NaN      NaN
35        4            7.6         0.36               NaN        NaN      NaN

## 과제2
- 데이터 : players.csv (kaggle NFL Big Data Bowl 2023 선수 데이터)
- 세션에 소개되지 않은 기능이 필요하다면, 구글링을 통해 구현해주시길 바랍니다.
- '내 드라이브'에 사본 저장 부탁드립니다.
- 데이터 설명:

|컬럼명|설명|
|--|---|
|nflId|Player identification number, unique across players (numeric)|
|height|Player height (text)|
|weight|Player weight (numeric)|
|birthDate|Date of birth (YYYY-MM-DD)|
|collegeName|Player college (text)|
|officialPosition|Official player position (text)|
|displayName|Player name (text)|

#### 데이터 불러오기 및 앞부분 확인

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [5]:
data = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/players.csv') # players.csv: '내 드라이브'에 사본 저장 후, 경로 수정
data.head()

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName
0,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady
1,28963,6-5,240,1982-03-02,"Miami, O.",QB,Ben Roethlisberger
2,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters
3,29851,6-2,225,1983-12-02,California,QB,Aaron Rodgers
4,30078,6-2,228,1982-11-24,Harvard,QB,Ryan Fitzpatrick

#### NaN, 데이터 타입, 개수 확인

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1679 entries, 0 to 1678
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nflId             1679 non-null   int64
 1   height            1679 non-null   object
 2   weight            1679 non-null   int64
 3   birthDate         1447 non-null   object
 4   collegeName       1455 non-null   object
 5   officialPosition  1679 non-null   object
 6   displayName       1679 non-null   object
dtypes: int64(2), object(5)
memory usage: 91.9+ KB

#### birthDate 컬럼으로 age 컬럼 추가하기

##### 1) birthDate 컬럼의 자료형을 object에서 datetime으로 전환

In [10]:
data['birthDate'] = pd.to_datetime(data['birthDate'])

##### 2) age 컬럼 생성, apply 및 lambda 함수를 써서 나이 계산

In [24]:
from datetime import datetime
today = datetime.now().date()

data['age'] = data['birthDate'].apply(lambda x : today.year - x.year)

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1679 entries, 0 to 1678
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nflId             1679 non-null   int64
 1   height            1679 non-null   object
 2   weight            1679 non-null   int64
 3   birthDate         1447 non-null   datetime64[ns]
 4   collegeName       1455 non-null   object
 5   officialPosition  1679 non-null   object
 6   displayName       1679 non-null   object
 7   age               1447 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 105.1+ KB

##### 3) age 결측치를 선수 평균 나이로 대체

In [32]:
mean = int(data['age'].mean()) # average age of Players
data['age'] = data['age'].fillna(mean)
data['age'] = data['age'].astype('int')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1679 entries, 0 to 1678
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nflId             1679 non-null   int64
 1   height            1679 non-null   object
 2   weight            1679 non-null   int64
 3   birthDate         1447 non-null   datetime64[ns]
 4   collegeName       1455 non-null   object
 5   officialPosition  1679 non-null   object
 6   displayName       1679 non-null   object
 7   age               1679 non-null   int64
dtypes: datetime64[ns](1), int64(3), object(4)
memory usage: 105.1+ KB

#### height 컬럼(feet-inch 형식)으로 heightCm 컬럼 추가하기

##### 1) heightCm 컬럼 생성, apply 및 lambda 함수를 사용해서 height 컬럼의 feet과 inch를 cm로 변환 ('-'를 기준으로 split해서 각각을 cm로 변환해 더하기)

In [75]:
data['heightCm'] = data['height'].apply(lambda x : x.split('-'))
data['heightCm'] = data['heightCm'].apply(lambda y : int(y[0])*30.48 + int(y[1])*2.54)
data.head(30)

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,age,heightCm
0,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,46,193.04
1,28963,6-5,240,1982-03-02,"Miami, O.",QB,Ben Roethlisberger,41,195.58
2,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,41,193.04
3,29851,6-2,225,1983-12-02,California,QB,Aaron Rodgers,40,187.96
4,30078,6-2,228,1982-11-24,Harvard,QB,Ryan Fitzpatrick,41,187.96
5,30842,6-6,267,1984-05-19,UCLA,TE,Marcedes Lewis,39,198.12
6,30869,6-7,330,1981-12-12,Louisiana State,T,Andrew Whitworth,42,200.66
7,33084,6-4,217,1985-05-17,Boston College,QB,Matt Ryan,38,193.04
8,33107,6-4,315,1985-08-30,Virginia Tech,T,Duane Brown,38,193.04
9,33130,5-10,175,1986-12-01,California,WR,DeSean Jackson,37,177.80
10,33131,6-8,300,1986-09-01,Miami,DE,Calais Campbell,37,203.20
11,33138,6-3,222,1985-07-02,Michigan,QB,Chad Henne,38,190.50
12,33241,6-3,219,1986-05-15,San Diego,QB,Josh Johnson,37,190.50
13,33566,5-11,185,1985-11-02,Texas Tech,WR,Danny Amendola,38,180.34
14,34452,6-3,220,1988-02-07,Georgia,QB,Matthew Stafford,35,190.50
15,34457,6-4,330,1987-01-25,Alabama,T,Andre Smith,36,193.04
16,34465,6-0,204,1987-12-20,Ohio State,SS,Malcolm Jenkins,36,182.88
17,34472,6-4,311,1985-11-19,California,C,Alex Mack,38,193.04
18,34540,6-5,254,1987-04-07,South Carolina,TE,Jared Cook,36,195.58
19,34654,5-11,195,1987-08-13,Rutgers,FS,Jason McCourty,36,180.34
20,34777,6-3,310,1986-01-03,Troy,NT,Steve McLendon,37,190.50
21,34843,6-2,215,1985-10-13,Michigan State,QB,Brian Hoyer,38,187.96
22,35441,6-4,313,1987-01-06,Nebraska,DE,Ndamukong Suh,36,193.04
23,35442,6-4,300,1988-02-25,Oklahoma,DT,Gerald McCoy,35,193.04
24,35443,6-5,320,1988-07-19,Oklahoma,T,Trent Williams,35,195.58
25,35446,5-11,195,1989-04-14,Florida,CB,Joe Haden,34,180.34
26,35449,6-3,304,1987-05-12,California,DE,Tyson Alualu,36,190.50
27,35452,6-2,265,1988-04-03,Michigan,DE,Brandon Graham,35,187.96
28,35454,6-5,275,1989-01-01,South Florida,DE,Jason Pierre-Paul,34,195.58
29,35459,5-10,185,1988-04-10,Alabama,SS,Kareem Jackson,35,177.80